# Generated by Django 4.2.6 on 2024-01-14 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_branch_address_alter_branch_contact_info'),
        ('employee', '0003_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_contacts', to='main.contact'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_addresses', to='main.address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(blank=True, help_text='date of employement', null=True),
        ),
    ]
