# Generated by Django 4.2.6 on 2024-01-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_department_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_addresses', to='main.address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_contacts', to='main.contact'),
        ),
    ]
