# Generated by Django 4.2.6 on 2024-01-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_address_created_by_address_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_info',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_types',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Phone', 'Phone'), ('email', 'email')], max_length=20),
        ),
    ]
