# Generated by Django 4.2.6 on 2024-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_department_office_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shifts',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
