# Generated by Django 4.2.6 on 2024-01-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_department_office_delete_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='shifts',
            new_name='shift',
        ),
    ]
