# Generated by Django 4.2.6 on 2024-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_designation_options_alter_role_options_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to='employee.employee'),
        ),
    ]
