# Generated by Django 4.2.6 on 2024-01-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in-progress', 'in-progress'), ('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=20),
        ),
    ]
