# Generated by Django 4.2.6 on 2024-01-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_attendence_checkintime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='working_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
