# Generated by Django 4.2.6 on 2024-01-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_attendence_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='working_hours',
            new_name='my_working_hours',
        ),
    ]
