# Generated by Django 4.2.6 on 2024-01-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_rename_working_hours_attendence_my_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='my_working_hours',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
