# Generated by Django 4.2.6 on 2024-01-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_remove_attendence_my_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='is_present',
            new_name='status',
        ),
        migrations.AddField(
            model_name='attendence',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendence',
            name='shift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
