# Generated by Django 4.2.6 on 2024-01-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0008_alter_attendence_checkintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='checkintime',
            field=models.DateTimeField(null=True, verbose_name='Check in time'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='checkouttime',
            field=models.DateTimeField(null=True, verbose_name='Check out time'),
        ),
    ]
